export const GITHUB_ISSUES_URL = "https://github.com/atisor73/ask-maroon/issues";

export const DEMO_QUERY = "jazz and music on the midway";

export const TOUR_STEPS = [
  {
    id: "query-guide",
    title: "Search here first",
    text:
      "Type a concept, event, person, or phrase. The model embeds your query, compares it with embedded archive chunks, and ranks the closest matches.",
    mode: "greedy",
    openAdvanced: false,
    leftPct: 39,
    topRem: 6,
    widthRem: 19,
    cardAnchorMode: "closest",
    dotLeftPct: 25,
    dotTopRem: 12,
  },
  {
    id: "backend-guide",
    title: "Vector backend",
    text:
      "This selects between embedding models. Retrieval quality, speed, and availability can vary by backend.",
    mode: "greedy",
    openAdvanced: false,
    leftPct: 1.5,
    topRem: 23,
    widthRem: 18,
    cardAnchorMode: "closest",
    dotLeftPct: 18,
    dotTopRem: 16.5,
  },
  {
    id: "advanced-guide",
    title: "Advanced search",
    text:
      "Filter results by year range and choose a search mode: 'Greedy search' returns the closest matches, while 'Exploratory sampling' draws from the top N documents for more varied, organic results.",
    mode: "greedy",
    openAdvanced: true,
    leftPct: 41,
    topRem: 17,
    widthRem: 20,
    cardAnchorMode: "closest",
    dotLeftPct: 21,
    dotTopRem: 20.25,
  },
  {
    id: "sampling-guide",
    title: "Top N + temperature",
    text:
      "Top N controls the pool we sample from. Temperature controls how deterministically we draw from that pool.",
    mode: "sample",
    openAdvanced: true,
    leftPct: 5,
    topRem: 37,
    widthRem: 18,
    cardAnchorMode: "closest",
    dotLeftPct: 5,
    dotTopRem: 35,
  },
  {
    id: "results-guide",
    title: "Ranked archive chunks",
    text:
      "Results appear here. We surface the best-matching documents, then use reverse highlighting to show which passages inside the chunk seem most relevant to the query.",
    mode: "sample",
    openAdvanced: true,
    leftPct: 2,
    topRem: 49,
    widthRem: 20,
    cardAnchorMode: "horizontal",
    dotLeftPct: 18.5,
    dotTopRem: 35.5,
  },
  {
    id: "viewer-guide",
    title: "Check the source issue",
    text:
      "The right side keeps the original PDF visible so readers can verify context quickly instead of trusting the snippet alone.",
    mode: "sample",
    openAdvanced: true,
    leftPct: 61.5,
    topRem: 9,
    widthRem: 18,
    cardAnchorMode: "closest",
    dotLeftPct: 67,
    dotTopRem: 15,
  },
  {
    id: "feedback-guide",
    title: "Send feedback",
    text:
      "If people get confused, open an issue so we can tighten the wording or add another annotation.",
    mode: "sample",
    openAdvanced: true,
    leftPct: 67.5,
    topRem: 32,
    widthRem: 16,
    cardAnchorMode: "closest",
    dotLeftPct: 73,
    dotTopRem: 39,
    linkLabel: "Open GitHub Issues",
    linkHref: GITHUB_ISSUES_URL,
  },
];
