export const GITHUB_ISSUES_URL = "https://github.com/atisor73/ask-maroon/";

export const DEMO_QUERY = "jazz and music around the midway";

export const TOUR_STEPS = [
  {
    id: "query-guide",
    title: "Search here first",
    text:
      "Type a concept, event, person, or phrase. The model embeds your query, compares it with embedded archive chunks, and ranks the closest matches. ",
    mode: "greedy",
    openAdvanced: false,
    leftPct: 41,
    topRem: 7,
    widthRem: 19,
    cardAnchorMode: "closest",
    dotLeftPct: 25,
    dotTopRem: 12,
  },
  {
    id: "backend-guide",
    title: "Vector backend",
    text:
      "This selects between embedding models. Retrieval quality, speed, and availability can vary by backend.",
    mode: "greedy",
    openAdvanced: false,
    leftPct: 1.5,
    topRem: 23,
    widthRem: 18,
    cardAnchorMode: "closest",
    dotLeftPct: 18,
    dotTopRem: 16.5,
  },
  {
    id: "advanced-guide",
    title: "Advanced search",
    text:
      "Filter results by year range and choose a search mode: 'Greedy search' returns the closest matches, while 'Exploratory sampling' draws from the top N documents for more varied, organic results.",
    mode: "greedy",
    openAdvanced: true,
    leftPct: 41,
    topRem: 17,
    widthRem: 20,
    cardAnchorMode: "closest",
    dotLeftPct: 21,
    dotTopRem: 20.25,
  },
  {
    id: "sampling-guide",
    title: "Top N + temperature",
    text:
      "Top N controls the pool we sample from. Temperature controls how deterministically we draw from that pool.",
    mode: "sample",
    openAdvanced: true,
    leftPct: 4,
    topRem: 39,
    widthRem: 30,
    cardAnchorMode: "closest",
    dotLeftPct: 8,
    dotTopRem: 35,
  },
  {
    id: "searching-guide",
    title: "Now searching...",
    text:
      "",
    mode: "sample",
    openAdvanced: true,
    leftPct: 24,
    topRem: 19,
    widthRem: 19,
    cardAnchorMode: "closest",
    dotLeftPct: 30,
    dotTopRem: 18,
    transient: true,
  },
  {
    id: "results-guide",
    title: "Ranked archive chunks",
    text:
      "Results appear here. Highlighting is applied after the embedding search and ranking, and estimates which phrases likely contributed to the high ranking - the entire text chunk is used in the similarity embedding.",
    mode: "sample",
    openAdvanced: true,
      leftPct: 5,
      topRem: 23,
      widthRem: 25,
      cardAnchorMode: "closest",
      dotLeftPct: 28,
      dotTopRem: 41,
    // leftPct: 42,
    // topRem: 35,
    // widthRem: 25,
    // cardAnchorMode: "horizontal",
    // dotLeftPct: 28,
    // dotTopRem: 41,
  },
  {
    id: "viewer-guide",
    title: "Check the source issue",
    text:
      "The right panel displays the original PDF issue of a selected result from the left panel. After a short delay, the viewer will navigate to the detected page.",
    mode: "sample",
    openAdvanced: true,
    leftPct: 61.5,
    topRem: 20,
    widthRem: 18,
    cardAnchorMode: "closest",
    dotLeftPct: 67,
    dotTopRem: 12,
  },
  {
    id: "feedback-guide",
    title: "Send feedback",
    text:
      "The Github resository contains more detailed notes on semantic retrieval. If you would like to report a bug or request a feature, please open an issue.",
    mode: "sample",
    openAdvanced: true,
    leftPct: 55,
    topRem: 3,
    widthRem: 22,
    cardAnchorMode: "closest",
    dotLeftPct: 90,
    dotTopRem: 3.5,
    linkLabel: "Open GitHub Repository",
    linkHref: GITHUB_ISSUES_URL,
  },
];

export const MOBILE_TOUR_STEPS = TOUR_STEPS.slice(0, -2);
