export const GITHUB_ISSUES_URL = "https://github.com/atisor73/ask-maroon/issues";

export const DEMO_QUERY = "jazz and music on the midway";

export const TOUR_STEPS = [
  {
    id: "query-guide",
    title: "Search here first",
    text:
      "Type a concept, event, person, or phrase. The model embeds your query, compares it with embedded archive chunks, and ranks the closest matches.",
    mode: "greedy",
    openAdvanced: false,
    leftPct: 41,
    topRem: 6,
    widthRem: 19,
    cardAnchorMode: "closest",
    dotLeftPct: 25,
    dotTopRem: 12,
  },
  {
    id: "backend-guide",
    title: "Vector backend",
    text:
      "This selects between embedding models. Retrieval quality, speed, and availability can vary by backend.",
    mode: "greedy",
    openAdvanced: false,
    leftPct: 1.5,
    topRem: 23,
    widthRem: 18,
    cardAnchorMode: "closest",
    dotLeftPct: 18,
    dotTopRem: 16.5,
  },
  {
    id: "advanced-guide",
    title: "Advanced search",
    text:
      "Filter results by year range and choose a search mode: 'Greedy search' returns the closest matches, while 'Exploratory sampling' draws from the top N documents for more varied, organic results.",
    mode: "greedy",
    openAdvanced: true,
    leftPct: 41,
    topRem: 17,
    widthRem: 20,
    cardAnchorMode: "closest",
    dotLeftPct: 21,
    dotTopRem: 20.25,
  },
  {
    id: "sampling-guide",
    title: "Top N + temperature",
    text:
      "Top N controls the pool we sample from. Temperature controls how deterministically we draw from that pool.",
    mode: "sample",
    openAdvanced: true,
    leftPct: 4,
    topRem: 38,
    widthRem: 24,
    cardAnchorMode: "closest",
    dotLeftPct: 7,
    dotTopRem: 35,
  },
  {
    id: "results-guide",
    title: "Ranked archive chunks",
    text:
      "Results appear here. Highlighting is applied after the search and estimate which parts likely contributed to the high ranking; it is not just the highlighted portion used in the similarity computation.",
    mode: "sample",
    openAdvanced: true,
    leftPct: 42,
    topRem: 35,
    widthRem: 25,
    cardAnchorMode: "horizontal",
    dotLeftPct: 28,
    dotTopRem: 40,
  },
  {
    id: "viewer-guide",
    title: "Check the source issue",
    text:
      "The right panel displays the original PDF issue of a selected result from the left panel. After a short delay, the viewer will navigate to the detected page.",
    mode: "sample",
    openAdvanced: true,
    leftPct: 61.5,
    topRem: 20,
    widthRem: 18,
    cardAnchorMode: "closest",
    dotLeftPct: 67,
    dotTopRem: 12,
  },
  {
    id: "feedback-guide",
    title: "Send feedback",
    text:
      "If something is confusing or counterintuitive, please open an issue on Github.",
    mode: "sample",
    openAdvanced: true,
    leftPct: 69,
    topRem: 32,
    widthRem: 16,
    cardAnchorMode: "closest",
    dotLeftPct: 67,
    dotTopRem: 39,
    linkLabel: "Open GitHub Issues",
    linkHref: GITHUB_ISSUES_URL,
  },
];
